# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build rest-api-news`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t rest-api-news`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system rest-api-news && \
          adduser --system -G rest-api-news rest-api-news

COPY dist/rest-api-news rest-api-news
RUN chown -R rest-api-news:rest-api-news .

CMD [ "node", "rest-api-news" ]
